import { Widget } from "./displayer/Widget.js";
import { Row } from "./displayer/Row.js";
import { Col } from "./displayer/Col.js";
import { Button } from "./displayer/Button.js";
import { IconButton } from "./displayer/IconButton.js";
import { Card } from "./displayer/Card.js";
import { Text } from "./displayer/Text.js";
import { Title } from "./displayer/Title.js";
import { Input } from "./displayer/Input.js";
import { RangeInput } from "./displayer/RangeInput.js";
import { NumericInput } from "./displayer/NumericInput.js";
import { Navbar } from "./displayer/navbar/Navbar.js";
import { NavbarItem } from "./displayer/navbar/NavbarItem.js";
import { Modal } from "./displayer/Modal.js";
let navbar = new Navbar("./assets/icons/favicon-32x32.png");
let ni1 = new NavbarItem();
navbar.addChild(ni1);
let ibtn = new IconButton("add","An Icon Button");
ni1.addChild(ibtn);
document.body.appendChild(navbar.element);
let r = new Row();
document.body.appendChild(r.element);
let c1 = new Col(6,6,6,6);
let c2 = new Col(6,6,6,6);
r.addChild(c1);
r.addChild(c2);
let ca2 = new Card("grey","pink");
c2.addChild(ca2);
let btn = new Button("A Button","pink");
btn.on("click",evt=>{
  m1.disabled=false;
  //enable the modal Here
});
let txt = new Text("hello I am a text.");
let ttl = new Title("A Title.");
let i = new Input("An Input.");
let ri = new RangeInput("A Range Input.");
let ni = new NumericInput("A Numeric Input.");
ca2.addChild(ttl);
ca2.addChild(txt);
ca2.addChild(btn);
ca2.addChild(i);
ca2.addChild(ri);
ca2.addChild(ni);
let m1=new Modal();
r.addChild(m1);
let m1title=new Title("modal title");
let m1text=new Text("modal text");
let m1btn = new Button("modal button","skyblue");
m1.addChild(m1title);
m1.addChild(m1text);
m1.addChild(m1btn);
